### ISSUE TITLE
Event handling

### ISSUE THREAD

**Issue by BrianTum** [steevjames/stories-for-flutter#2]
How do I handle events such as:  on story start, on story end?

**Comment by BrianTum** [comment]
For story and story items!

**Comment by steevjames** [comment]
Will try to add that as well in a few weeks.

**Comment by BrianTum** [comment]
By the way, this is the best story package. Hope to see an update soon.
Let me make these recommendations:
 - Event handling
 - Description text for images/videos
 - Swipe down to dismiss the stories/pop context
 - Show Date-Time the post uploaded in the stories
 - Progress timer

I would like to help where I can. I'm deeply interested in this package!

**Comment by steevjames** [comment]
Thanks for the compliment. It means a lot. Currently a bit busy, but will do it soon. I'll close the issue when changes are made so that you'll be notified.
In the meantime, if you would like to make changes/improvements feel free to do so. :)

**Comment by BrianTum** [comment]
Welcome. I forked it and gonna do some twerks and send you what I get as well.
